### ISSUE TITLE
returnType is being changed by fetch* methods

### ISSUE THREAD

**Issue by gietos** [thephpleague/csv#139]
I believe this is simply a typo, but why returnType is being changed to array in the fetch() method:

https://github.com/thephpleague/csv/blob/81d465ed62a0e8da4777964fed82e28d21bbf40f/src/Reader.php#L95

That leads to unexpected behavior in some cases. Example:

```php
$reader = Reader::createFromString('field1,field2' . PHP_EOL . 'value1,value2');
$reader->setReturnType(Reader::TYPE_ITERATOR);
var_dump(gettype($reader->fetchAssoc()));
// object
var_dump(gettype($reader->fetchAssoc()));
// array
```

**Comment by gietos** [comment]
Oh, now I see, that is expected, there's even test for that (testReturnTypeResetBetweenCallToArray)
Why, then?

**Comment by nyamsprod** [comment]
There are 2 main reasons for that:

- All previous version of the library returned an `array` (So for a BC perspective it makes sense IMHO)

- Changing the return type of a method is something that I would not advocate to begin with. If I had to choose I'd always return a `Iterator` and do a full BC break. but in this case this is a trade-off. [People expressed](https://twitter.com/nyamsprod/status/667643120616652800) that having both return type could be beneficial when dealing with all sorts of CSV (small vs large). 

So Instead of creating 3 new methods

- `fetchAssocIterator($offset_or_keys = 0, callable $callable = null) Iterator`
- `fetchColumnIterator(int $columnIndex = 0, callable $callable = null) Iterator`
- `fetchPairsIterator(int $offsetColumnIndex = 0, (int $valueColumnIndex = 1, callable $callable = null) Generator`

or adding a extra argument to each method like having 

- `fetchAssoc($offset_or_keys = 0, callable $callable = null, $returnType = Reader::TYPE_ARRAY)`
- `fetchColumn(int $columnIndex = 0, callable $callable = null, $returnType = Reader::TYPE_ARRAY);`
- `fetchPairs(int $offsetColumnIndex = 0, (int $valueColumnIndex = 1, callable $callable = null, $returnType = Reader::TYPE_ARRAY);`

I choose instead to enable return type changes with a specific method.

By resetting this behavior on each call you requires the user to explicitly state what return type he/she expects when using the method. This way whenever you receive a Reader object you have full control over what it can return.

**Comment by gietos** [comment]
> BC perspective

You're working on new major version, right? So isn't it totally okay to get BC broken?

> By resetting this behavior on each call you requires the user to explicitly state what return type he/she expects when using the method. This way whenever you receive a Reader object you have full control over what it can return.

Here you've got object's state being changed implicitly. User sets property of an object, she expects that object configured respectively, not a method. It's totally unclear, that by setting a property you're going to affect only one future method call. If you choose to go with the property, just don't reset it after call.

**Comment by nyamsprod** [comment]
> You're working on new major version, right? So isn't it totally okay to get BC broken?

The main reason for the BC breakage is the modification of the callable signature on two Reader extract methods (fetchAssoc and fetchColumn). Everything else is just added features. By minimizing BC breakage even between major versions you improve your library code while helping its adoption rate.

> It's totally unclear, that by setting a property you're going to affect only one future method call.

On contrary this is how the Reader class query options have always worked since version 4.0 :) . Quoting [the documentation](http://csv.thephpleague.com/query-filtering/)

> After an extract/conversion method call, all query options are cleared;

You should think of the Reader as a double purpose object :

- a CSV accessor which returns a result set of CSV rows
- a CSV Query builder which defined this result set further 

In v8 the query builder will have a new feature which is to defined its result set type using the new including the  `setReturnType` method. At least this is how I view this method

**Comment by nyamsprod** [comment]
After some discussions on [thephpleague mailing list](https://groups.google.com/forum/#!topic/thephpleague/NQUSkD3K-Ek)  the following changes were made:

- the `setReturnType` method was removed
-  Methods return `Iterator` where applicable (i.e.: `fetchAssoc`, `fetchColumn`, `fetchPairs`) 
- The `fetchPairs` method will always preserve the offset keys and their correspondant value.
- The `fetchPairsWithoutDuplicates` was added. The method returns an `array` where duplicates offset have their value overwritten.

Hope these changes will satisfy you. They are already present on the master branch. Documentation update will be done shortly

**Comment by gietos** [comment]
:+1: thanks a lot for your work!

**Comment by nyamsprod** [comment]
Documentation is updated could you close this issue if all is good. Thanks in advance
