### ISSUE TITLE
Append rows to a file

### ISSUE THREAD

**Issue by abrahammontas** [thephpleague/csv#150]
Every time I need to update a file, I have to read the it and save on memory to append the new rows and then overwrite the content.

**Comment by nyamsprod** [comment]
This is the expected behaviour according to the documentation so I don't understand the issue ?

**Comment by abrahammontas** [comment]
is not an issue just a new feature.

**Comment by nyamsprod** [comment]
What you are requesting is not possible because of the way PHP reads a CSV. The document is treated as a stream so you can write a new one or append an existing one but you can not update selected rows without at least a temporary file. 
I would be more than happy to review a PR with your feature request if you can preserve the file cursor position between updates.

**Comment by abrahammontas** [comment]
sorry if I misspoke, my comment was just to try to improve the library.
Do not think that I did a critique. On the contrary, I used the library many times and it works very well for me.
I just said my opinion to express what could be ideal. I would love to be part of the contributors, i am willing to try and join your list. :) @nyamsprod

**Comment by nyamsprod** [comment]
@abrahammontas I did not take it as a critique I've only highlighted the issues with your proposed feature. 

As for submitting a PR, you don't need to be part of the phpleague to contribute to the library, just submit your work following the rules explained it the [contribution guide](https://github.com/thephpleague/csv/blob/master/CONTRIBUTING.md) and I'll be more than happy to review it
