### ISSUE TITLE
Deprecation of League\Csv\Reader::fetch

### ISSUE THREAD

**Issue by JC5** [thephpleague/csv#208]
`League\Csv\Reader::fetch` has been marked as [deprecated](http://csv.thephpleague.com/changelog/) as per the change log but it is still used as a main example in the "[reading](http://csv.thephpleague.com/reading/)" section of the manual and there does not seem to be any indication this method is actually deprecated, nor what the alternative should be.

**Comment by nyamsprod** [comment]
@JC5 yes indeed it is marked as deprecated because works as starrted on the next major release and Reader::fetch will be indeed removed from the public API in the next major release. This is the reason it is marked as deprecated. There's no alternative right now for its usage but marking it like that is a hint to users that this method will be removed. AFAIK this does not in any way prevents anyone from using the method right now.

Hope this answer your question as it is similar to #206

**Comment by JC5** [comment]
It does, apologies. I am used to deprecation _after_ the new method has been presented. :wink:

**Comment by joshbrw** [comment]
I came here for this exact reason. Shouldn't the method be deprecated once an alternative is available?

**Comment by nyamsprod** [comment]
@joshbrw Please refer to [PHPdoc documentation](https://phpdoc.org/docs/latest/references/phpdoc/tags/deprecated.html)

**Comment by joshbrw** [comment]
@nyamsprod Surely these methods are going to be superceded by some other method? The PHPDoc documentation states `If it is superceded by another method it is RECOMMENDED to add a @see tag in the same PHPDoc pointing to the new element.`, which is what I'd have expected.

**Comment by nyamsprod** [comment]
> If it is superceded by another method
there's a If at the start of the sentence :)

**Comment by joshbrw** [comment]
Of course. But surely you're always going to need to `fetch` data from the CSV, no?

**Comment by nyamsprod** [comment]
yes and having a `@deprecated` in the docblock does not mean that the method won't work anymore.. it is an indication about where the package will go next. Really I don't see the problem with this ? This is informative only.

**Comment by joshbrw** [comment]
I guess it all depends on your view of what `deprecated` means. My IDE (PHPStorm) throws up a usage warning if the method is used.

**Comment by nyamsprod** [comment]
> I guess it all depends on your view of what deprecated means

Nope. The definition of `@deprecated` is the one PHPdoc put out and this is the one I'm following. I could rephrase that by saying that It depends on how PHPStorm interprets it :) .

**Comment by cdekok** [comment]
@nyamsprod static analyzers don't like it either and any ide.. if there is no alternative it's not nice to mark it as deprecated.

**Comment by joshbrw** [comment]
@cdekok I don't think we're going to get our way with this one, but I whole-heartedly agree with you.

**Comment by alexeyshockov** [comment]
Agree with @joshbrw. When I see a deprecated method, I always try to refactor the code. But in this case I'm unable to do that.

By using `@deprecated` just to notify users, you push them to pay less attention to really deprecated things (because they cannot fix all `@deprecated` issues from now). And after some time with a bunch of such issues unresolved you just stop paying attention to them.

> If it is superceded by another method

Of course, you are right that providing an alternative is not required. But `Reader` is the only class to read content from a CSV file (in the library), and, deprecating of its main methods without providing an alternative, you deprecate the whole task of reading CSV.

So I'm puzzled now, because I want to read a CSV file, but I don't know how to do it properly (with `league/csv`).

Just my 5 cents.

**Comment by nyamsprod** [comment]
At everyone, I had a discussion off record with other leaguers and I decided to make a patch release which will remove most of the `@deprecated`. Once the others bug fixes are reviewed the patch will be released later this week of next week.

**Comment by joshbrw** [comment]
Thanks @nyamsprod - appreciate it!

**Comment by nyamsprod** [comment]
version 8.2.1 is out with the fix

**Comment by alexeyshockov** [comment]
Thanks, @nyamsprod!
