### ISSUE TITLE
 Exception while save file

### ISSUE THREAD

**Issue by yupe** [thephpleague/csv#220]
## Issue summary

Exception while save file

> 
Exception 'TypeError' with message 'Return value of League\Csv\StreamIterator::getCurrentLine() must be of the type string, boolean returned'

in /vendor/league/csv/src/StreamIterator.php:219

### System informations

League\Csv - ^9.0@dev
PHP - PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
OS Platform - UBUNTU 16.04

## Standalone code, or other way to reproduce the problem

```php
<?php

$writer = Writer::createFromPath('path/to/csv', 'w+');
$writer->insertOne(['title1', 'title2', 'title3']);
$writer->insertOne(['row1', 'row1', 'row2']);
$writer->output();
```

### Expected result
Created file without exceptions

### Actual result
Created file with exception

**Comment by nyamsprod** [comment]
@yupe Thanks for the reported bug... as I'm still working on v9 this will be fix in the next commit.

As a side note in your example you have created a CSV file with the `w` open mode flag and then used the `ouput` method on it. This is not recommended because the method will reset the CSV document pointer and anything written will be truncated as per `w` expected usage. This is true in v8 as well. An alternative would be to use `w+` instead, for instance.

**Comment by nyamsprod** [comment]
The bug fix has landed on the master branch I'll close this issue.
