### ISSUE TITLE
Can't find the way to reuse the object for creating new CSV file?

### ISSUE THREAD

**Issue by php-** [thephpleague/csv#225]
Hello
I tried to create a csv files from Csv\Writer, but can't reuse the same object, even cloning does not work, there is no reset or clearing functionality to refresh and create new csv file
Anything on this?
Thanks

**Comment by nyamsprod** [comment]
HI @php- did you read the documentation as this is well explained there.

**Comment by php-** [comment]
I could not find it, thats why I asked you.

On 27 Apr 2017 03:13, "ignace nyamagana butera" <notifications@github.com>
wrote:

HI @php- <https://github.com/php-> did you read the documentation as this
is well explained there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thephpleague/csv/issues/225#issuecomment-297631462>,
or mute
the thread

**Comment by nyamsprod** [comment]
Well since I don't know what you are trying to accomplish I can't help you what I can tell you is what's written in the documentation :
- the Writer is constructed to work with a single file at once 
- the Writer relies on stream and SplFileObject meaning you can't use cloning
- the Writer actions are based on the open_mode arguments from fopen (to be simple)
So:
    - cloning the Writer is not possible since cloning a stream resource ou SplFileObject is not possible
    - iterate over a Writer object is highly discourage because of cursor pointer loss and open_mode choice (may erase your CSV document on rewind for instance)

Again this information is present in the documentation so I don't know what else you need.

**Comment by php-** [comment]
Thanks a lot, that's what I needed.
love you:*
