### ISSUE TITLE
Tagged release which includes forced field enclosure feature not yet available

### ISSUE THREAD

**Issue by btmash** [thephpleague/csv#265]
## Issue summary

First off, I just want to say this is an amazing library and makes my life easier working with/manipulating csv files :)

I wasn't sure where this issue goes but at the moment, I see there is a force enclosure feature documentation on http://csv.thephpleague.com/9.0/interoperability/enclose-field/. With that said, it phrases that feature to be available for 9.1.0 but at the moment there is no branch tag with 9.1.0. Is the recommended approach to bring the feature in via master (I see the docs at https://github.com/thephpleague/csv/blob/master/docs/9.0/interoperability/enclose-field.md so would I file a PR to update that instead?

**Comment by nyamsprod** [comment]
Yes, use the master there are still some ironing that needs to be applied before releasing 9.1.0

**Comment by btmash** [comment]
Cool, thanks for the clarification. Should the docs for this be updated so it can say 'feature is available in master and upcoming 9.1.0 release'? Its not a long while away so its not a dealbreaker but figure might as well be accurate if possible.

**Comment by nyamsprod** [comment]
@btmash usually I update the doc when a feature is complete otherwise I forgot about it because the doc is on the master it get updated when the new feature land. It's easier for me to maintain the library like that. 
In the meantime as far as I remember nothing prevents you from copying the EncloseField class and use it with the current stable release. This is just enhancement so nothing is update elsewhere in the code.

**Comment by btmash** [comment]
Ah, ok. It makes sense 😄 Again, thanks for the clarification. Will close out the issue.
