### ISSUE TITLE
Append row to Csv

### ISSUE THREAD

**Issue by fcorbi** [thephpleague/csv#273]
## Issue summary

Append row to csv

## Standalone code, or other way to reproduce the problem
//with file.csv already populated with some rows

$writer = Writer::createFromPath("file.csv");
$writer->insertOne(["a", "b"]);

### Expected result
file contains some rows plus new rows

### Actual result
file contains new rows that override the original rows

**Comment by nyamsprod** [comment]
this is expected behavior please read the documentation to select the appropriate open mode.

**Comment by fcorbi** [comment]
Open writer with flags "a+" resolve the problem, but i think that this has to be more clear in the first page of docs. Thanks anyway

**Comment by nyamsprod** [comment]
It is written in the documentation

**Comment by cdunlap** [comment]
I know this issue is old, and maybe it _was_ in the documentation. However there is no example for appending records in the current documentation--at least that I could find. Without knowing that the read mode strings translate directly into standard PHP file modes, appending records to a CSV file with this library isn't obvious.

The name of the method also suggests, at least to me, that it adds a record much like a SQL INSERT statement would. The documentation in the code itself for that particular method also says "Adds a single record to a CSV document." implying that it isn't overwriting anything but instead appending.

I'll submit a PR for your documentation sometime within the next couple days. Thanks for the hard work you've put into this!

**Comment by auralon** [comment]
I still can't find an example of appending data to a CSV. Can any please share an example of using the open mode "a+"?

**Comment by nyamsprod** [comment]
You can find the documentation on how to load correctly your CSV under the following page 
https://csv.thephpleague.com/9.0/connections/instantiation/

The `$mode` is explained in https://www.php.net/manual/en/function.fopen.php#refsect1-function.fopen-parameters
