### ISSUE TITLE
League\Csv\ stream. php may have problems

### ISSUE THREAD

**Issue by HaozhouChen** [thephpleague/csv#331]
### Bug Report
```php
public function seek($position)
    {
        if ($position < 0) {
            throw new Exception(sprintf('%s() can\'t seek stream to negative line %d', __METHOD__, $position));
        }

        $this->rewind();
        while ($this->key() !== $position && $this->valid()) {
            $this->current();
            $this->next();
        }

        $this->offset--;
        $this->current();
    }
```

If  `$opsition` is equal to 0, then `$this->offset` is equal to minus 1

**Comment by nyamsprod** [comment]
if `$position` is equal to `0` then your code `$this->offset` is equal at `1` in the loop and end up being equal to `0` after the loop 😉

**Comment by CoderChenHZ** [comment]
If `$position` is equal to 0, then it won't enter the loop, so `$offset--` after `$this->offset` is -1.

**Comment by nyamsprod** [comment]
why won't it enter the loop ???

**Comment by CoderChenHZ** [comment]
`$this->rewind()` result return `$this->offset = 0`, so `$this->key() === $position`,so won't enter the loop.😝

**Comment by nyamsprod** [comment]
yes but we don't really care because the `current()` method does not use the offset property which will be incremented to `0` when `next()` is used. I'll look into it after work but yeah there should not be any issue in how the `Stream` class is used in the package. Since the class is marked as `@internal`  we are safe but I can look into it to see if some use cases may end up in error. If you could provide such example It would be easier to investigate/fix but I don't see an instance where this could come up 🤔

**Comment by nyamsprod** [comment]
seems to be easy to fix... I'm in the process of releasing 9.2.0... I'll create a small branch with the fix and add it to the release. The way the Stream class is used in the package is not impacted by this bug but fixing it is still possible and will be addressed. If you prefer to submit a PR you are welcomed to do it also in the meantime 😉

**Comment by CoderChenHZ** [comment]
Yes, this problem has no impact on the use of the basic, but if the user use `key()` may cause a little ambiguity, so, I submitted a PR , 😝
