### ISSUE TITLE
getRecords indexed array from 1

### ISSUE THREAD

**Issue by tebaly** [thephpleague/csv#334]
### Bug Report

| Information | Description |
|--------------|---------|
| Version | 9.2 |
| PHP version | 7.3 |
| OS Platform | Linux |

#### Summary

different array indexes

#### Standalone code, or other way to reproduce the problem

````
        $csv = Reader::createFromPath($filePath, 'r');
        $csv->setHeaderOffset(0);
        $records = $csv->getRecords(); // indexed from #1  
 
        $record = $csv->fetchOne(1); // indexed from 0, return record #2   
````

#### Expected result

getRecords indexed array from 0  

#### Actual result

getRecords indexed array from 1

**Comment by nyamsprod** [comment]
@tebaly thanks for using the library.

Please refers to the [documentation](https://csv.thephpleague.com/9.0/) website as this is expected behaviour. 
```php
<?php
$csv->setHeaderOffset(0);
$records = $csv->getRecords(); // indexed from #1  
```
Since the first record is used as the CSV header it is removed from iteration hence iteration starts at `#1` .

```php
<?php
$record = $csv->fetchOne(1); // indexed from 0, return record #2   
```

The `ResultSet` does not re-order the CSV so using `fetchOne(1)` means your are fetching the nth_records starting from the first row (ie: you start at 1 and search for the nth_record from 1 = you are getting the second index.. as expected.

Remember your are using a StreamIterator that's why we are not re-indexing everytime the index to preserve index loss between objects.

**Comment by tebaly** [comment]
Link works. But where is it written about? I have not found any references or descriptions.

````
//by setting the header offset we index all records
//with the header record and remove it from the iteration
````
There is not written about the indexes. After all, you can remove headers and rewrite indises starting from 0, But you **do not do** it

## The problem is different

It is expected that you did not change the indexes again. **But you do it**

````
        $csv = Reader::createFromPath($filePath, 'r');
        $csv->setHeaderOffset(0); // REMOVE HEADERS, Index [0]
        $record = $csv->fetchOne(1); // Fetch FIRST record, expected
````
After `setHeaderOffset(0)` expected same index behavior. 
I thought.

**Comment by nyamsprod** [comment]
@tebaly you Can found the info for how fetchOne works using this link https://csv.thephpleague.com/9.0/reader/resultset/#selecting-a-specific-record
