### ISSUE TITLE
What about using security by design at least for preventing possible csv injections?

### ISSUE THREAD

**Issue by robertfausk** [thephpleague/csv#453]
|    Q        |   A
|------------ | ------
| Version     | 9.7.3

## Question

Currently an user has to use ```EscapeFormula``` manually on each writer.
E.g. like in https://github.com/knutschsoft/swapp/commit/31b59da408562df3f155f9c119e19c0a8fc007e5
```PHP
$csv = Writer::createFromString();
$csv->addFormatter(new EscapeFormula("'", ['=', '-', '+', '@', '\t', '\r']));
```

What about using ```EscapeFormula``` by default and let users of this lib explicitly opt out?
On the one hand, this would increase security, but on the other hand it would also lead to a BC.

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have read, search and not found the information on the [documentation website](https://csv.thephpleague.com).
* [x] I have read, search and not found the information on PHP related forums and/or websites.
* [x] This issue is about 1 question around the package with no business or domain specific logic related to a specific situation.
* [x] The question has a descriptive title. For example:  "Can I use the library with compressed CSV documents ?".

**Comment by nyamsprod** [comment]
@robertfausk thanks for using the library and providing the updated default values. I have already release a new version with your patch. That being said I do not believe it is the responsibility of the library to opt out from this behaviour. To be totally transparent I believe the current set up to force opt-in is the best one. As described in the documentation

> Even though we provide the EscapeFormula formatter I must stress out that this is in no way a bulletproof method. This prevention mechanism only works if you know how the CSV export will be consumed. In any other cases, you are better of leaving the filtering to the consuming client and report any found security concern to their respective security channel.

In other word I believe it is up to the consuming party to deal with this security concern because as a transporting layer a CSV on itself does not present any security issue, at least not in this topic. Furthermore

- The security issue is created by the consuming application in this case spreadsheet applications and their filtering/validation rules that are out of scope from this library intent.
- Why should we impose people who are not using spreadsheet applications the burden to add more filtering rules in their applications that **do** comply with CSV basic rules ?
- Having a transparent opt-in feature makes the intent clear and security is not hidden
- Last but not least having the feature decoupled from the main functionality makes the whole library easier to maintain and avoid architectural issue like having the infamous `$escape` parameter added to CSV process in PHP.

The `EscapeFormula` class is a trade-off between how CSV should be generated and how it is actually used.
