### ISSUE TITLE
Better way to guess the delimiter

### ISSUE THREAD

**Issue by tacman** [thephpleague/csv#529]
I'm not sure of the delimiter in my csv / txt files, so I wrote this.

But it doesn't seem very elegant, and I was wondering if you had a better way to do it.  Also, what do you think of letting the library handle this, like setAutoDelimiter()?  

```php
        if (in_array($ext, ['tsv', 'csv', 'txt'])) {
            $csvReader = Reader::createFromPath($fn, 'r');
            $result = Info::getDelimiterStats($csvReader, ["\t", ','], 3);
            // pick the highest one
            arsort($result);
            $csvReader->setDelimiter(array_key_first($result));
```

Thanks again for a rocking library!

**Comment by nyamsprod** [comment]
@tacman as stated in the documentation the method only returns hints because sometimes and more often than not the detected delimiter is not the correct one. Hence why the returned array is not sorted. At the end of it all, the best and only way to know the delimiter is asking the CSV provider the delimiter used to generate the CSV document. Anything else is at best approximation.
