### ISSUE TITLE
Is there a way to filter out duplicated rows from a csv ?

### ISSUE THREAD

**Issue by nasser-rawashdeh** [thephpleague/csv#542]
_(Fill in the relevant information below to help triage your issue.)_

|    Q        |   A
|------------ | ------
| Version     | 9.0

### Short background:
I accept a CSV file from the user, and I aim to parse and consume it.
As the system is agnostic to duplicated lines, they disappear when processed, 
but then the numbers I report don't match.

### Actual question
What is the best way to detect the number of duplicated rows, or filter them out ?

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have read, searched and not found the information on the [documentation website](https://csv.thephpleague.com).
* [x] I have read, searched and not found the information on PHP related forums and/or websites.
* [x] This issue is about 1 question around the package with no business or domain specific logic related to a specific situation.
* [x] The question has a descriptive title. For example:  "Can I use the library with compressed CSV documents ?".

**Comment by nyamsprod** [comment]
@nasser-rawashdeh thanks for using the package. 

Filtering out duplicate row is IMHO a domain specific issue which is not limited to CSV but to any tabular or collection of data. the CSV provided by the packate is an Iterator or array records. If you can filter out duplicates from a database you can apply the same technique to league/csv. In other word the problem you are trying to resolve is:

- not specific to CSV
- not resolved by the package because it depends on a lot of outside parameters the package will never be knowledgable about

so **no** de-duplicating a CSV is not handle and is considered out of context for this package.
