### ISSUE TITLE
empty columns trigger duplicate column names error

### ISSUE THREAD

**Issue by lcdservices** [thephpleague/csv#543]
## Bug Report

| Information | Description |
|--------------|---------|
| Version | 9.19.0 |
| PHP version | 8.1.31 |
| OS Platform | CloudLinux v7.9.0 |

### Summary

When importing a CSV file that has empty columns, a "duplicate column names" error is thrown when calling getHeader(). According to the documentation, extra fields should be truncated. I've examined the raw text file and the extra columns are "clean" -- there are no characters between the commas delineating columns. I don't see anything in the documentation suggesting additional steps required to auto-truncate these fields. Ref: https://csv.thephpleague.com/9.0/reader/

### Standalone code, or other way to reproduce the problem

```
$csv = Reader::createFromPath($file['name'], 'r');
$csv->setHeaderOffset(0);
$csv->setEscape('');
$header = $csv->getHeader();
$records = $csv->getRecords();
```

### Expected result

Empty columns ignored/truncated and getHeader() returns column names without error.

### Actual result

Error thrown.

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/thephpleague/csv/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/thephpleague/csv/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by nyamsprod** [comment]
@lcdservices thanks for using the package. I believe you misread the documentation or perhaps the documentation is not clear enough.
when using the setHeaderOffset the package will use the selected record as header.
Upon selection the package will examine the content of the selected record.
In you case you seem to have multiple empty columns which means that the record you selected contains multiple fields with empty value which result in the error you are seeing.
To avoid that error you can either stop using ay header at all OR when using a retrieving method like `getRecords` or `getRecordsAsObject` fill in the `$heaader` parameters which will superseed the header record.
What you are describing is expected behaviour.
