### ISSUE TITLE
detectDelimiterList() don't find the correct delimiter

### ISSUE THREAD

**Issue by Heart1010** [thephpleague/csv#55]
I have the following csv file (without a csv header), line 1:
```
Surname;Name;;;;;3316157;12360000;"Bank name";DE49123600000003316157;GENODIF1DIR;12,456
```
With this line detectDelimiterList() can't find the correct delimiter:

```php
$delimiters_list = $inputCsv->detectDelimiterList();

if (!$delimiters_list) {
    //no delimiter found
} elseif (1 == count($delimiters_list)) {
    $delimiter = $delimiters_list[0]; // the found delimiter
} else {
    //inconsistent CSV 
    var_dump($delimiters_list); // all the delimiters found
}
```
shows:
```php
array(2) {
  [0]=>
  string(1) ","
  [1]=>
  string(1) ";"
}
```

**Comment by nyamsprod** [comment]
a BC break has been introduced in League/csv so it will go 7.0 hopefully next week or the week after. So we could take this opportunity to add the "weigh" information. We have 2 possibilities:
- major BC break the return array looks like this
```php
[ "'" => 123, "\t" => 12]
//the key represents the the delimiter,  the value number of delimiter found.
```
or
- less BC break the return array looks like this
```php
[ 123 => "'",  12 => "\t"]
//the key represents the number of delimiter found, the value the delimiter
```
I'm in favor of the latter as it brings less breakage... the code provided by the documentation for instance would still work. The only breakage would be the key index and meaning

Thought ?

**Comment by Heart1010** [comment]
Thanks for bringing this up again.... the latter is also my favorite :+1:

**Comment by nyamsprod** [comment]
great so its a done deal then as it is already fixed that way in the dev-master  :+1: I'll re-close this issue then

**Comment by stof** [comment]
@nyamsprod using the occurence of the delimiter as key hasa big drawback: keys must be unique. If 2 delimiters have the same occurence, you will loose one of them in the output.

**Comment by nyamsprod** [comment]
Indeed your right :+1: . How do you propose we resolve this issue ?  The only sane way to do so is to use the previous suggested output

```php
[ "'" => 123, "\t" => 12]
//the key represents the the delimiter,  the value number of delimiter found.
```

the only problem is that it brings BC break :-1:  What we can do in the meantime is document this bug and then fix it properly with a new version. Hopefully after I finish with 7.1 a 8.0 version will be introduced with this bug fix and a rewrote Reader class. What do you think about this roadmap ?

**Comment by nyamsprod** [comment]
Another solution which would be less BC break would be to have the following output:

```php
[ 
    123 => "'",
    12 => "\t",
     3 => [",", ";"],
]
//the key represents the number of delimiter found, the value the delimiter
//in case a of same occurence we return an array of delimiters 
```

Thought ?

**Comment by nyamsprod** [comment]
@stof @Heart1010 @cordoval 

After a good week-end thinking over this bug I think I found a fix ... so here's what I propose which won't even need a BC break :+1:

When for the same occurence we get multiple answers then we will get a "word" instead of a single character this his how it will look like:

```php
$reader = Reader::createFromPath('/path/to/your/csv/file.csv');
$delimiters_list = $reader->detectDelimiterList(10, [' ', '|']);
//let's pretend that "|" appears as often as the ";" delimiters will get the following result.
$delimiters_list = [
...
     5 => ";|",
...
];
```
We can take advantage of the language constructs and do the following:
```php
$list_all_delimiters_found = str_split($delimiters_list[5]);
```
If you are only interested in having only one result you can do as follow:
```php
$delimiter = array_shift($delimiters_list)[0]; //which will always return the first character found
```
What's great with this last piece of code is that if we decide to switch from a word to a real array in v8 this code will still work out of the box.

If you like this fix please respond here ASAP so I can implement it and release v7.1

**Comment by Heart1010** [comment]
I'm fine with this approach!

The doc (http://csv.thephpleague.com/properties/) should be enhanced with this info or better show a "use out of the box example" which first checks if there are more than one delimiters found with same occurence and so on...

**Comment by stof** [comment]
@nyamsprod returning a word is also a BC break as it changes the API too. There is no way to fix it without any BC break

**Comment by nyamsprod** [comment]
@stof hmm I don't think so as it does not alter the return type per se. You do expect a string anyway ? so the method signature is not changed IMHO

**Comment by stof** [comment]
@nyamsprod currently, values in the returned arrays are always potential delimitors. After your proposal, ``;|`` is **not** a potential delimitor; ``;`` and ``|`` are.
so any code using this method to find a delimitor would become broken. Currently, they will just miss one candidate. With your proposal, they will miss 2 candidates until they update their code.

**Comment by nyamsprod** [comment]
@stof Okay I get your point. So here's what I propose then:

@Heart1010 @cordoval 

- I will leave the current behaviour as it is right now and **document it properly on the CSV documentation website**.
- I will release 7.1.
- A patch improving the method will land in v8 with a BC break (with full documentation and a migration code attached to it as I always do).
- This issue will remain open until a patch is released in v8.

As a reminder, this method has been stated from the beginning as giving hints, as such it can be wrong and has been improved since its introduction in v5. So in v8 it will be improve again.  As a side note, I  would question the CSV provider if I were given the task to parse such CSV (**this is in no way a justification for not patching the method**).

Thought ?

**Comment by nyamsprod** [comment]
The documentation website is updated http://csv.thephpleague.com/properties/#detecting-csv-delimiter

**Comment by nyamsprod** [comment]
The address this bug without BC break a new method has been created `fetchDelimitersOccurrence` and the current `detectDelimiterList` method will be deprecated in the next release 7.2.0 and remove in the next major release 8.0. The changes are already effective in the master. If you want to test the new method.

**Comment by nyamsprod** [comment]
This issue is fixed in the master branch
